spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TCG-Pokermon
    username: postgres
    password: kauan123

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: pokermon

  security:
    secret-key: bgn578nv04lig2394tpcgsjag4a83pht3utlhahukwgby382b82obg85y42gb2mc2rf42ofunqiqao

external:
  pokemon-pictures-url: https://github.com/HybridShivam/Pokemon/blob/master/assets/images